sudo: false

language: android

jdk: oraclejdk8

notifications:
  email: true

before_script:
  - android-wait-for-emulator
  - adb shell input keyevent 82

install:
  - ./gradlew clean assembleDebug testDebug assembleAndroidTest --stacktrace -PdisablePreDex

script:
  - ./gradlew testDebug connectedCheck --stacktrace -PdisablePreDex

before_cache:
  - rm -f  $TRAVIS_BUILD_DIR/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $TRAVIS_BUILD_DIR/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $TRAVIS_BUILD_DIR/.gradle/caches/
    - $TRAVIS_BUILD_DIR/.gradle/wrapper/
    - $TRAVIS_BUILD_DIR/.android/build-cache

before_install:
  # Reduce memory usage / avoid OutOfMemoryError with Gradle 4.10.3+
  - echo "org.gradle.jvmargs=-Xmx2048m -Xms512m -XX:MaxPermSize=768m" >> gradle.properties
  # Make Gradle wrapper executable.
  - chmod +x gradlew
  # Silence warning.
  - mkdir -p ~/.android
  - touch ~/.android/repositories.cfg
  # Install SDK license so Android Gradle plugin can install deps.
  - mkdir "$ANDROID_HOME/licenses" || true
  # Accept licenses before installing components, no need to echo y for each component
  - yes | sdkmanager --licenses
  # Install the rest of tools (e.g., avdmanager)
  - sdkmanager tools
  # Install the system image
  - sdkmanager "system-images;android-22;default;armeabi-v7a"
  # Create and start emulator for the script. Meant to race the install task.
  - echo no | avdmanager create avd --force -n test -k "system-images;android-22;default;armeabi-v7a"
  - $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window &
